# Generated by Django 5.0.2 on 2024-02-27 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='from_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='to_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
